### PR TITLE
feat: Implement UI for create and update

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Creates a new template that will be used for both 'create' and 'update', create-update.html`. The fields are disabled and enabled based on whether they are editable in each state, 'create' and 'update'.
- When the form is rendered for 'update', the data for the relevant asset is passed to the template and the form is pre-filled with existing asset information. This is accomplished partly using Jinja and partly with JS

## QA

- Check out this feature branch and run the project
- Navigate to the 'Add asset' tab (http://0.0.0.0:8017/manager/create) and attempt to upload an asset, making sure to test each field. It would be a good idea to test with different combinations of fields and, when relevant, test with different amounts of inputs ie. on tags.
- Navigate to the asset update page, (http://0.0.0.0:8017/manager/update?file-path=FILE_PATH), and see that the fields you previously selected/input are already filled in. Update some fields and click update, see you are redirected to the same page but with the relevant fields updated.
- Make sure it matches the design/fields/descriptions ect in the [figma](https://www.figma.com/design/dOz7GIHMmofSdje0l0pVFs/Asset-manager?node-id=12-4914&node-type=frame&t=rS6m8vOfxnAr0WK0-0) and [spec](https://docs.google.com/document/d/1QzAjI0OfjagcuGtfZpKv2h31tyAhM4-cjL0xa-2dXW8/edit)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-13751

### CODE REVIEW

**Comment by immortalcodes** [comment]
Are we covering all the languages that are required here?

image

Also if there is just one langauge could we say "select the language which applies".

**Comment by immortalcodes** [comment]
Also if I specifically not press enter after every tag, it will take the entire tag array as a single tag
image
This is true for UI atleast

**Comment by immortalcodes** [comment]
Base64 encoding failed here
image

**Comment by immortalcodes** [comment]
image
For some reason tags didn't went through and I think it is because I just typed them and didn't press enter.
Please ignore this if this is supposed to be the design

**Comment by immortalcodes** [comment]
Update asset should take me to the home screen but it does not
image

**Comment by petesfrench** [comment]
> Are we covering all the languages that are required here?
> 
> image
> 
> Also if there is just one langauge could we say "select the language which applies".

Definitely not covering all language here. If we want to cover all language we will have to implement something a little more advanced to make it easier to find the appropriate language. But given that this is an MVP, this is fine for now.

In the figma it is a multiselect. Why? I do not know haha

**Comment by petesfrench** [comment]
@immortalcodes 

**For the tags section**, I am not sure the proper UX pattern follow here. The figma said to use search and filter, but there is nothing to search so I tried to adapt it. I will ask @Sophie-32 tomorrow.

**For the non-image asset not having names**, where can you see this in the spec? I don't see why we would do that.

**For failed base64 encoding**, I have hopefully fixed this [in the next PR](https://github.com/canonical/assets.ubuntu.com/pull/253/files)

**For the second tags comments**, this again related to the UX of how it should work. Will address tomorrow with Sophie's input.

**For redirecting after editing**, yes this is temporary until we have a 'details' page. Which is being added [in the next PR](https://github.com/canonical/assets.ubuntu.com/pull/253/files).

**Comment by immortalcodes** [comment]
> @immortalcodes
> 
> **For the tags section**, I am not sure the proper UX pattern follow here. The figma said to use search and filter, but there is nothing to search so I tried to adapt it. I will ask @Sophie-32 tomorrow.
> 
> **For the non-image asset not having names**, where can you see this in the spec? I don't see why we would do that.
> 
> **For failed base64 encoding**, I have hopefully fixed this [in the next PR](https://github.com/canonical/assets.ubuntu.com/pull/253/files)
> 
> **For the second tags comments**, this again related to the UX of how it should work. Will address tomorrow with Sophie's input.
> 
> **For redirecting after editing**, yes this is temporary until we have a 'details' page. Which is being added [in the next PR](https://github.com/canonical/assets.ubuntu.com/pull/253/files).

Makes sense, for the name thing here is the comment that says add name if it's a PDF. Not sure if this is valid for all.
https://www.figma.com/design/dOz7GIHMmofSdje0l0pVFs?node-id=12-4914#945668040

**Comment by immortalcodes** [comment]
There are few things that are still in discussion and might need correction later(with more clarity from design and UX), We could also plan a bit of refactoring in later stages, but this is really good work and checks everything for MVP.
Cheers!

**Review by immortalcodes — APPROVED** [review]

**Pull request merged**
